name: Echo Environments

on:
  push:
    branches:
      - main
      - staging

jobs:
  echo-env:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     environment: [production, staging]

    # environment: ${{ matrix.environment }}
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} # Choose the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display environment variable
        run: echo "MY_ENV_VAR is ${{ VAR.ENV }}"
